# Generated by Django 4.2.30 on 2026-07-13 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_url_fallback',
            field=models.URLField(blank=True, help_text='Fallback URL if image is not uploaded yet', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('casa', 'Casa'), ('dep', 'Departamento'), ('terreno', 'Terreno'), ('local', 'Local Comercial')], default='casa', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
