# Generated by Django 4.2.30 on 2026-07-13 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property_image_property_image_url_fallback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('PAYPHONE', 'Payphone (Tarjeta)'), ('DEUNA', 'DeUna'), ('TRANSFER', 'Transferencia Bancaria')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID del pago en Payphone o Referencia Bancaria', max_length=100, null=True)),
                ('receipt_image', models.ImageField(blank=True, help_text='Comprobante de pago para métodos manuales', null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
