# Generated by Django 4.2.30 on 2026-07-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Total de visitas al detalle de la propiedad'),
        ),
    ]
