# Generated by Django 4.2.30 on 2026-07-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_property_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Área en metros cuadrados', max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Número de baños', max_digits=4),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0, help_text='Número de habitaciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve descripción del usuario/corredor', null=True),
        ),
    ]
